require_relative 'array/count_array'
require_relative 'array/increase_array'
require_relative 'array/select_array'
require_relative 'array/split_array'
require_relative 'string/camelcase_string'
require_relative 'string/count_string'
require_relative 'string/palindrome_string'
require_relative 'zandelok/functions'
